### ISSUE TITLE
Ejemplo de .pre-commit-config.yaml

### ISSUE THREAD

**Issue by vicgalle** [Komorebi-AI/python-template#14]
```
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
        - id: check-case-conflict
        - id: check-json
        - id: check-symlinks
        - id: check-yaml
        - id: destroyed-symlinks
        - id: fix-byte-order-marker
        - id: fix-encoding-pragma
          args: [--remove]
        - id: mixed-line-ending
          args: [--fix=lf]
        - id: requirements-txt-fixer
        - id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        name: isort (python)
-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
```
