### ISSUE TITLE
Cachear dependencias en Github Actions

### ISSUE THREAD

**Issue by albertotb** [Komorebi-AI/python-template#19]
Para acelerar las Actions, se pueden cachear tanto las dependencias de Python como las de Conda. Referencias:
- https://github.com/marketplace/actions/setup-miniconda#caching
- https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#caching-dependencies
- https://github.com/actions/cache/blob/main/examples.md#python---pip

**Comment by albertotb** [comment]
Ejemplo del repositorio de `satlink-autokat`:

```
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
```
