### ISSUE TITLE
Pre commit `uv lock`

### ISSUE THREAD

**Issue by albertotb** [Komorebi-AI/python-template#55]
La nueva versión del repo oficial de pre-commit de uv añade un hook para asegurar que el `uv.lock` está actualizado. Aunque no es imprescindible, ya que se actualiza cada vez que se hace un `uv add`, puede ser interesante añadirlo:

```
- repo: https://github.com/astral-sh/uv-pre-commit
  # uv version.
  rev: 0.4.9
  hooks:
    # Update the uv lockfile
    - id: uv-lock
```
